#ifndef DIALOG_2_WINDOW_H
#define DIALOG_2_WINDOW_H

// ATTEN - None of that 'namespace' stuff here.
//         Do a direct 'include' to the 'ui' header file
#include <QDialog>

#include "ui_dialog_2.h" // <-- Generated by qtcreator from dialog_2.ui

// Per ui definition, inherit from 'QDialog' class/widget
class Dialog_2_Window : public QDialog
{
    Q_OBJECT

public:
    Dialog_2_Window(QWidget *parent = nullptr);
    ~Dialog_2_Window();

private slots:

    void dialog_2_update_button_clicked();

private:
    Ui_Dialog_2_Window *ui;   // <--- Class declared in 'ui_dialog_2.h

    unsigned int count = 0;
};
#endif // DIALOG_2_WINDOW_H

/* EOF */

