#ifndef DIALOG_1_WINDOW_H
#define DIALOG_1_WINDOW_H

// ATTEN - None of that 'namespace' stuff here.
//         Do a direct 'include' to the 'ui' header file
#include <QDialog>

#include "ui_dialog_1.h" // <-- Generated by qtcreator from dialog_1.ui

// Per ui definition, inherit from 'QDialog' class/widget
class Dialog_1_Window : public QDialog
{
    Q_OBJECT

public:
    Dialog_1_Window(QWidget *parent = nullptr);
    ~Dialog_1_Window();

private slots:

    void dialog_1_push_1_clicked();

    void dialog_1_OK_button_clicked();

private:
    Ui_Dialog_1_Window *ui;   // <--- Class declared in 'ui_dialog_1.h
};
#endif // DIALOG_1_WINDOW_H

/* EOF */

