#ifndef DIALOG_3_WINDOW_H
#define DIALOG_3_WINDOW_H

// ATTEN - None of that 'namespace' stuff here.
//         Do a direct 'include' to the 'ui' header file
#include <QDialog>

#include "ui_dialog_3.h" // <-- Generated by qtcreator from dialog_3.ui

// Per ui definition, inherit from 'QDialog' class/widget
class Dialog_3_Window : public QDialog
{
    Q_OBJECT

public:
    Dialog_3_Window(QWidget *parent = nullptr);
    ~Dialog_3_Window();

private slots:

    void dialog_3_radio_button_clicked();

private:
    Ui_Dialog_3_Window *ui;   // <--- Class declared in 'ui_dialog_3.h
};
#endif // DIALOG_3_WINDOW_H

/* EOF */

