//============================================================================
// FILE: data_entry.cpp
//
// DESCRIPTION:
//    Manages the 'data-entry' panel.  Extracts the data from the
//    text-fiels and writes them (as ASCII text) to a file.
//============================================================================
#include <iostream>
#include <fstream>

#include "data_entry.h"
#include "ui_data_entry.h"

//========================================================
// METHOD: data_entry
//
// DESCRIPTION:
//    Constructor as entry point to create the GUI/Window
//    of the application.  The 'data_entry' object
//    inherits a 'QMainWindow' and a 'ui'.  While I don't
//    know what those are, I think they're the entry
//    points that create the base graphics objects that
//    constitue the GUI.
//
//    This code was auto-generated by the 'Qt Creator'
//    tool.  So be carefull if changing things.
//
//    The 'ui' object, amazingly, appears to be the root
//    to all the objects (widgets?) of the entire GUI.
//========================================================
data_entry::data_entry(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::data_entry)
{
    ui->setupUi(this);
}

//========================================================
// METHOD: ~data_entry
//
// DESCRIPTION:
//    Class destructor.
//========================================================
data_entry::~data_entry()
{
    delete ui;
}


//========================================================
// METHOD: on_exit_button_clicked
//
// DESCRIPTION:
//    A button 'callback' in Qt are called 'slot'.  You
//    mouse-button-2 select the button widget and the
//    pop-up menu will show the various possible ways
//    to define 'slot' functions.  Select "clicked" and
//    the following, but empty, function is created.
//
//    They probably have a default 'exit' handler, but
//    this is my home-grown one.
//========================================================
void data_entry::on_exit_button_clicked()
{
    std::exit(0);
}

//========================================================
// METHOD: on_cancel_button_clicked
//
// DESCRIPTION:
//    Clears the text in all of the text-field widgets.
//========================================================
void data_entry::on_cancel_button_clicked()
{
    ui->name_text_field->clear();
    ui->address_text_field->clear();
    ui->city_text_field->clear();
    ui->state_text_field->clear();
    ui->zip_text_field->clear();
    ui->phone_text_field->clear();
}


//========================================================
// METHOD: on_save_button_clicked 
//
// DESCRIPTION:
//    Extracts the data from each of the text-field
//    widgets (to what's called a 'QString' object).
//
//    Converts the 'QString' to a std::string for each
//    date-entry item.  All data strings are concatenated
//    to a result string.  It's saved (as ASCII text) to
//    a file "results.txt" ... and also sent to <stdout>.
//========================================================
void data_entry::on_save_button_clicked()
{
    QString tmp = ui->name_text_field->text();

    std::string name = tmp.toStdString();

    tmp = ui->address_text_field->text();

    std::string address = tmp.toStdString();

    tmp = ui->city_text_field->text();

    std::string city = tmp.toStdString();

    tmp = ui->state_text_field->text();

    std::string state = tmp.toStdString();

    tmp = ui->zip_text_field->text();

    std::string zip = tmp.toStdString();

    tmp = ui->phone_text_field->text();

    std::string phone = tmp.toStdString();

    std::string separator = "----------------------------\n";

    std::string all_data = separator +
                           "Name.....: " + name    + "\n" +
                           "Address..: " + address + "\n" +
                           "City.....: " + city    + "\n" +
                           "State....: " + state   + "\n" +
                           "ZIP......: " + zip     + "\n" +
                           "Phone....: " + phone   + "\n" +
                           separator;

    std::cout << all_data;

    std::ofstream fd("results.txt", std::ios::out); // overwrite

    if (fd.is_open())
    {
        fd << all_data;
    
        fd.close();
    }
    else
    {
        std::cout << "***> ERROR - cannot open file\n";
    }
}

/* EOF */

