//============================================================================
// FILE: graphics_palette.cpp
//
// DESCRIPTION:
//    Code generated by question to "insightGPT".
//============================================================================
#include <QPainter>
#include <QPaintEvent>

#include "graphics_palette.h"

GraphicsPalette::GraphicsPalette(QWidget *parent)
   : QWidget(parent)
{
   // Optional: give the widget a background colour
   setAutoFillBackground(true);

   QPalette pal = palette();

   pal.setColor(QPalette::Window, Qt::white);

   setPalette(pal);
}
 
void GraphicsPalette::paintEvent(QPaintEvent *event)
{
    Q_UNUSED(event);

    QPainter painter(this);

    painter.setRenderHint(QPainter::Antialiasing, true);

    // Example: draw a rectangle
    painter.setPen(QPen(Qt::darkBlue, 2));

    painter.setBrush(QBrush(Qt::cyan));

    painter.drawRect(20, 20, width() / 2 - 40, height() / 2 - 40);

    // Example: draw an ellipse
    painter.setPen(QPen(Qt::darkRed, 3));

    painter.setBrush(QBrush(Qt::magenta));

    painter.drawEllipse(width() / 2 + 10,
                        height() / 2 + 10,
                        width() / 2 - 30,
                        height() / 2 - 30);

    // Example: draw a line
    painter.setPen(QPen(Qt::green, 4, Qt::DashLine));

    painter.drawLine(0, height() - 1, width() - 1, 0);
}

/* EOF */

