//============================================================================
// FILE: graphics_palette.cpp
//
// DESCRIPTION:
//    Code generated by question to "insightGPT".
//============================================================================
#include <QPainter>
#include <QPaintEvent>

#include "graphics_palette.h"

GraphicsPalette::GraphicsPalette(QWidget *parent)
   : QWidget(parent)
{
   pal = palette();

   // Optional:
   //    The palette (by default) has a 'clear' background.  So
   //    anything drawn in the main 'canvas' will show through
   //    to the palette.  Thus, anything drawn in the 'canvas' AND
   //    the 'palette' will both be shown.
   //
   //    But use the following to set a 'background' color that
   //    is not 'clear'.
   //          setAutoFillBackground(true);
   //          pal.setColor(QPalette::Window, Qt::white);
   //    For now, leave it 'clear'.

   // Change the default application palette to 'pal'
   setPalette(pal);
}

void GraphicsPalette::update_grid()
{
    if (draw_grid)
    {
        draw_grid = false;
    }
    else
    {
        draw_grid = true;
    }

    update();
}

void GraphicsPalette::update_line()
{
    if (draw_line)
    {
        draw_line = false;
    }
    else
    {
        draw_line = true;
    }

    update();
}

void GraphicsPalette::update_circle()
{
    if (draw_circle)
    {
        draw_circle = false;
    }
    else
    {
        draw_circle = true;
    }

    update();
}

void GraphicsPalette::update_oval()
{
    if (draw_oval)
    {
        draw_oval = false;
    }
    else
    {
        draw_oval = true;
    }

    update();
}

void GraphicsPalette::update_sine()
{
    if (draw_sine)
    {
        draw_sine = false;
    }
    else
    {
        draw_sine = true;
    }

    update();
}

void GraphicsPalette::update_cosine()
{
    if (draw_cosine)
    {
        draw_cosine = false;
    }
    else
    {
        draw_cosine = true;
    }

    update();
}

void GraphicsPalette::update_tangent()
{
    if (draw_tangent)
    {
        draw_tangent = false;
    }
    else
    {
        draw_tangent = true;
    }

    update();
}

void GraphicsPalette::update_cotangent()
{
    if (draw_cotangent)
    {
        draw_cotangent = false;
    }
    else
    {
        draw_cotangent = true;
    }

    update();
}

void GraphicsPalette::update_secant()
{
    if (draw_secant)
    {
        draw_secant = false;
    }
    else
    {
        draw_secant = true;
    }

    update();
}

void GraphicsPalette::update_cosecant()
{
    if (draw_cosecant)
    {
        draw_cosecant = false;
    }
    else
    {
        draw_cosecant = true;
    }

    update();
}
 
void GraphicsPalette::paintEvent(QPaintEvent *event)
{
    Q_UNUSED(event);

    QPainter painter(this);

    painter.setRenderHint(QPainter::Antialiasing, true);

    if (draw_grid)
    {
        painter.setPen(Qt::blue);

        x = width() / 2;
        y = height();

        const QLine x_axis(x, 0, x, y);

        painter.drawLine(x_axis);

        x = width();
        y = height() / 2;

        const QLine y_axis(0, y, x, y);

        painter.drawLine(y_axis);
    }

    if (draw_line)
    {
        painter.setPen(Qt::red);

        x = width();
        y = height();

        QPoint first(0, y);
        QPoint last(x, 0);

        painter.drawLine(first, last);

        update();
    }

    if (draw_circle)
    {
        // There's no 'drawCircle()'.  Use 'drawEllipse()' whose
        // rectangle is a square.
        painter.setPen(Qt::green);

        x = width() / 2;
        y = height() / 2;

        int width = x / 4;

        QPoint upper_left(x - width, y - width);
        QPoint lower_right(x + width, y + width);

        QRectF rectangle(upper_left, lower_right); // a square

        painter.drawEllipse(rectangle);
    }

    if (draw_oval)
    {
        painter.setPen(Qt::magenta);

        x = width() / 6;
        y = height() / 6;

        QPoint upper_left(x, y);
        QPoint lower_right(x + 160, y + 290);

        QRectF rectangle(upper_left, lower_right); // a rectangle 

        painter.drawEllipse(rectangle);
    }
}

/* EOF */

