//============================================================================
// FILE: text_palette.cpp
//
// DESCRIPTION:
//    Code generated by question to "insightGPT" on how to implement a
//    text/graphics pane.
//============================================================================
#include <QPainter>
#include <QPaintEvent>

#include "text_palette.h"

TextPalette::TextPalette(QWidget *parent)
    : QWidget(parent)
{
    QPalette pal = palette();

    setPalette(pal);
}

void TextPalette::update_grid()
{
    if (draw_grid)
    {
        draw_grid = false;
    }
    else
    {
        draw_grid = true;
    }

    update();
}

void TextPalette::paintEvent(QPaintEvent *event)
{
    Q_UNUSED(event);

    QPainter painter(this);

    painter.setRenderHint(QPainter::Antialiasing, true);

    if (draw_grid)
    {
        painter.drawText(5, 20, "GRID: ON");
    }
    else
    {
        painter.drawText(5, 20, "GRID: OFF");
    }
}

/* EOF */

