//============================================================================
// FILE: text_palette.cpp
//
// DESCRIPTION:
//    Code generated by question to "insightGPT" on how to implement a
//    text/graphics pane.
//============================================================================
#include "text_palette.h"
#include <QFont>

TextPalette::TextPalette(QWidget *parent)
    : QTextEdit(parent)
{
    // Set a readable default font
    QFont f("Consolas", 10);

    f.setStyleHint(QFont::Monospace);

    setFont(f);

    // Optional placeholder text
    setPlaceholderText("Enter your notes or formatted text here...");
}

/* EOF */

