//============================================================================
// FILE: text_palette.cpp
//
// DESCRIPTION:
//    Code generated by question to "insightGPT" on how to implement a
//    text/graphics pane.
//============================================================================
#include <QPainter>
#include <QPaintEvent>

#include "text_palette.h"

TextPalette::TextPalette(QWidget *parent)
    : QWidget(parent)
{
    QPalette pal = palette();

    setPalette(pal);
}

void TextPalette::paintEvent(QPaintEvent *event)
{
    Q_UNUSED(event);

    QPainter painter(this);

    painter.setRenderHint(QPainter::Antialiasing, true);

    painter.drawText(5, 20, "text here");
}

/* EOF */

