#!C:/Tcl/bin/tclsh
# ************************************************************************
# FILE: make_wheel.tcl
#
# DESCRIPTION:
#    Tcl script that generates three "wheels" used to encrypt/decrypt
#    a document using an "engigma" cipher.
#
#    See the DESCRIPTION in encrypt_doc.tcl
#
#    This program will generate three consecutive arrays of 256 bytes
#    of randomly generated one-byte values that represent the three
#    "wheels" to mimic the encryption used in the "enigma" machine.
#
#    The total size of the file will be, of course, 3 * 256 = 768 bytes.
#
#    The first wheel will be [0 .. 255], second wheel [256 .. 511], and
#    the third wheel will be [512 .. 767].
#
#    USAGE:
#      tclsh85 make_wheels.tcl <output-doc> <seed>
#
#    EXAMPLE:
#      tclsh85 make_wheels.tcl wheel.bin 136
#*************************************************************************


# ***********************************************
# PROCEDURE NAME: show_usage
#
# DESCRIPTION:
#    Invoked when wrong command-line args
#    are given.
# ***********************************************
proc show_usage { } {

  puts "***> ERROR - Invalid args"
  puts "***> USAGE:"
  puts "***>    make_wheels.tcl <wheel-file-out> <seed>"
  puts "***> EXAMPLE:"
  puts "***>    make_wheels.tcl wheels.bin 136"
}


# ***********************************************
# PROCEDURE NAME: generate_wheels
#
# DESCRIPTION:
#    Generates three consecutive arrays of
#    randomly generated bytes, each array being
#    256 bytes long.
#
#    These arrays will be used as input to
#    encrypt and decrypt data files using a
#    pseudo-enigma protocol.
# ***********************************************
proc generate_wheels { tofile seed } {

  puts "---> Procedure: generate_wheels"
  puts "---> To......: $tofile"

  set len [expr 3 * 256]

  set to_fd [open "$tofile" wb+]

  for { set i 0 } { $i < $len } { incr i } {
      #
      # Invoke rand() to generate a floating point value
      # between (0.0 and 1.0), not incluing 0.0 or 1.0.
      #
      #set value [expr ::tcl::chan::random ]
      set value [ ::tcl::mathfunc::rand ]

      #
      # Convert to an integer.
      #
      set value [expr $value * 1000.0]
      set value [expr round($value)]

      set byte [expr ($value % 256)]

      if { $byte < 256 } {
         puts $to_fd "$byte"
      }
  }

  close $to_fd
}


# ***********************************************
# PROCEDURE NAME: main ... sort of ...
#
# DESCRIPTION:
#    Executing commands begins here ...
# ***********************************************
puts "Begin - $argv0"

if { $argc != 2 } {

  show_usage

  exit
}

set wheels_file [lindex $argv 0]
set seed        [lindex $argv 1]

generate_wheels $wheels_file $seed

puts "End - $argv0"

